# Use root/example as user/password credentials
## https://hub.docker.com/_/mysql
### https://phoenixnap.com/kb/mysql-docker-container

version: '3'
services:
  db:
    image: mysql:5.7.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
     - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql:ro
    ports:
      - 127.0.0.1:3357:3306
      - 33570:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: croot
      MYSQL_PASSWORD: password
# https://forums.docker.com/t/how-to-fix-that-mysql-deny-in-docker-container-by-interaction/45627/5
# https://www.techrepublic.com/article/how-to-deploy-and-use-a-mysql-docker-container/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080



